# Generated by Django 4.0.3 on 2022-03-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0056_c8message_is_rated'),
    ]

    operations = [
        migrations.CreateModel(
            name='chat_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lists', models.CharField(max_length=5000)),
                ('admin_profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='customer.profile')),
            ],
        ),
    ]
