# Generated by Django 4.0.3 on 2022-03-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_list',
            name='lists',
            field=models.JSONField(max_length=5000),
        ),
    ]
