# Generated by Django 4.0.3 on 2022-03-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADMIN', '0002_alter_chat_list_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_list',
            name='lists',
            field=models.JSONField(blank=True, max_length=5000, null=True),
        ),
    ]
