# Generated by Django 3.2.4 on 2021-06-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_profile_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_location',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='user_location',
            name='long',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
