# Generated by Django 3.2.4 on 2021-06-26 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20210626_0827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_location',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='user_location',
            name='long',
        ),
        migrations.AddField(
            model_name='user_location',
            name='latitude',
            field=models.DecimalField(decimal_places=5, default=155.55, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_location',
            name='longitude',
            field=models.DecimalField(decimal_places=5, default=555.555, max_digits=9),
            preserve_default=False,
        ),
    ]
