# Generated by Django 3.2.4 on 2021-06-26 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20210626_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_location',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='customer.profile'),
        ),
        migrations.CreateModel(
            name='user_adress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=600)),
                ('delivery_adress', models.BooleanField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adress', to='customer.profile')),
            ],
        ),
    ]
