# Generated by Django 3.2.4 on 2021-06-26 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0042_area'),
        ('customer', '0009_auto_20210626_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_adress',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.city'),
        ),
    ]
