# Generated by Django 3.2.4 on 2021-06-26 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0042_area'),
        ('customer', '0010_user_adress_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_adress',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.area'),
        ),
    ]
