# Generated by Django 3.2.4 on 2021-06-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('customer', '0011_user_adress_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_adress',
            name='area',
        ),
        migrations.RemoveField(
            model_name='user_adress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user_adress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_location',
            name='user',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='user_adress',
        ),
        migrations.DeleteModel(
            name='user_location',
        ),
    ]
