# Generated by Django 3.2.4 on 2021-06-26 12:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Phone',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator('^(01|\\+8801)[37985]\\d*$')], verbose_name='Phone Number'),
        ),
    ]
