# Generated by Django 3.2.4 on 2021-06-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Phone',
            field=models.IntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
