# Generated by Django 3.2.4 on 2021-06-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0025_alter_profile_current_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_adress',
            name='delivery_parson_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
