# Generated by Django 3.2.4 on 2021-06-28 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_user_adress_delivery_parson_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_adress',
            name='Phone',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Phone Number'),
        ),
    ]
