# Generated by Django 3.2.4 on 2021-06-28 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0028_alter_user_adress_delivery_adress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_adress',
            name='delivery_adress',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
