# Generated by Django 3.2.5 on 2021-07-04 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0030_customer_bags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer_bags',
        ),
    ]
