# Generated by Django 3.2.5 on 2021-07-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0033_rename_user_customer_bags_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_bags',
            name='profile',
        ),
    ]
