# Generated by Django 3.2.5 on 2021-07-06 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_product_city'),
        ('customer', '0037_alter_customer_bags_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_bags',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Product.product'),
        ),
    ]
