# Generated by Django 3.2.5 on 2021-07-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0038_alter_customer_bags_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_adress',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
