# Generated by Django 3.2.5 on 2021-07-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0040_alter_user_adress_updated_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_adress',
            name='updated_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
