# Generated by Django 3.2.5 on 2021-07-19 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0042_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
