# Generated by Django 3.2.5 on 2021-07-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0043_profile_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='C8Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomId', models.IntegerField()),
                ('message', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_profile_c8messages', to='customer.profile')),
            ],
        ),
    ]
