# Generated by Django 3.2.5 on 2021-07-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0044_c8message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c8message',
            name='id',
        ),
        migrations.AlterField(
            model_name='c8message',
            name='roomId',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
