# Generated by Django 3.2.5 on 2021-07-20 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0045_auto_20210720_0720'),
    ]

    operations = [
        migrations.AddField(
            model_name='c8message',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='c8message',
            name='roomId',
            field=models.IntegerField(),
        ),
    ]
