# Generated by Django 3.2.5 on 2021-07-24 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0051_basic_setting_side_bar_image'),
        ('customer', '0047_auto_20210724_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='current_city',
            field=models.ForeignKey(blank=True, default='Dhaka', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_current_profile', to='root.city'),
        ),
    ]
