# Generated by Django 3.2.5 on 2021-08-01 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_email_verify_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='asdasdsad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asdaaa', to='customer.profile')),
            ],
        ),
    ]
