# Generated by Django 3.2.5 on 2021-08-01 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0052_asdasdsad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='asdasdsad',
        ),
    ]
