# Generated by Django 3.2.6 on 2021-08-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0055_alter_user_location_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='c8message',
            name='is_rated',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
