# Generated by Django 4.0.3 on 2022-03-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0056_c8message_is_rated'),
    ]

    operations = [
        migrations.AddField(
            model_name='c8message',
            name='distanation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_profile_dis_c8messages', to='customer.profile'),
        ),
    ]
