# Generated by Django 4.0.3 on 2022-03-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0057_c8message_distanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c8message',
            name='distanation',
        ),
    ]
