# Generated by Django 3.2.4 on 2021-06-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_image',
            name='id',
        ),
        migrations.AlterField(
            model_name='product_image',
            name='position',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
