# Generated by Django 3.2.4 on 2021-06-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_product_image_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_image',
            name='position',
            field=models.AutoField(help_text='asd', primary_key=True, serialize=False, unique=True),
        ),
    ]
