# Generated by Django 3.2.4 on 2021-06-22 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_image_position'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product_image',
        ),
    ]
