# Generated by Django 3.2.4 on 2021-06-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Amount',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
