# Generated by Django 3.2.4 on 2021-06-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0010_product_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Menu',
        ),
    ]
