# Generated by Django 3.2.4 on 2021-06-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_remove_product_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='menu',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
