# Generated by Django 3.2.4 on 2021-06-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0033_auto_20210623_2043'),
        ('Product', '0013_remove_product_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.menu'),
        ),
    ]
