# Generated by Django 3.2.4 on 2021-06-23 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0033_auto_20210623_2043'),
        ('Product', '0015_alter_product_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='root.menu'),
        ),
    ]
