# Generated by Django 3.2.4 on 2021-06-25 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_alter_product_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, help_text='It use to facting product form url', null=True, verbose_name='Product slug'),
        ),
    ]
