# Generated by Django 3.2.5 on 2021-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0043_alter_area_city'),
        ('Product', '0017_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.ManyToManyField(blank=True, related_name='city_related_product', to='root.City'),
        ),
    ]
