# Generated by Django 3.2.5 on 2021-07-10 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0041_alter_user_adress_updated_time'),
        ('root', '0043_alter_area_city'),
        ('Product', '0018_product_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('PN', 'Pending'), ('PS', 'Processing'), ('SF', 'Successful'), ('CN', 'Cancelled')], default='PN', max_length=2)),
                ('track_ip', models.GenericIPAddressField()),
                ('delivery_time', models.DateTimeField()),
                ('ordered_time', models.DateTimeField(auto_now_add=True)),
                ('bag_json', models.JSONField()),
                ('home_adress', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.user_adress')),
                ('payment_method', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.payment_options_allow')),
                ('product', models.ManyToManyField(blank=True, to='Product.Product')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_user_order', to='customer.profile')),
            ],
        ),
    ]
