# Generated by Django 3.2.5 on 2021-07-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0050_basic_setting_reusable_html_content'),
        ('Product', '0019_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(default='Cash on delivery', null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.payment_options_allow'),
        ),
    ]
