# Generated by Django 3.2.5 on 2021-07-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_auto_20210711_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(),
        ),
    ]
