# Generated by Django 3.2.5 on 2021-07-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0022_alter_order_delivery_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_reusableBag',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
