# Generated by Django 3.2.5 on 2021-07-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0023_order_is_reusablebag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_reusableBag',
            field=models.PositiveIntegerField(blank=True),
        ),
    ]
