# Generated by Django 3.2.5 on 2021-07-12 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0024_alter_order_is_reusablebag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='is_reusableBag',
            new_name='reusableBag_price',
        ),
    ]
