# Generated by Django 3.2.5 on 2021-07-12 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0025_rename_is_reusablebag_order_reusablebag_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_offer',
            field=models.PositiveIntegerField(blank=True, default=2),
            preserve_default=False,
        ),
    ]
