# Generated by Django 3.2.5 on 2021-07-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0026_order_discount_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_offer',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3),
        ),
    ]
