# Generated by Django 3.2.5 on 2021-07-12 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0028_alter_order_discount_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
