# Generated by Django 3.2.5 on 2021-07-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0029_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_offer',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price',
            field=models.FloatField(default=0),
        ),
    ]
