# Generated by Django 3.2.5 on 2021-07-12 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0030_auto_20210712_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='discount_offer',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
