# Generated by Django 3.2.5 on 2021-07-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0031_alter_order_discount_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_report',
            field=models.CharField(blank=True, choices=[('Product quality was bad', 'Product quality was bad'), ('Wrong product', 'Wrong product'), ('Missing product', 'Missing product'), ('Expired product', 'Expired product'), ("Missing Matol's", "Missing Matol's"), ("I didn't like the packaging", "I didn't like the packaging"), ('My order arrived late', 'My order arrived late'), ('Delivery man was unprofessional', 'Delivery man was unprofessional'), ('Other', 'Other')], max_length=40, null=True),
        ),
    ]
