# Generated by Django 3.2.5 on 2021-07-15 01:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0033_order_starts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='starts',
        ),
        migrations.AddField(
            model_name='order',
            name='stars',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.RegexValidator(regex='^[0-5]$')]),
        ),
    ]
