# Generated by Django 3.2.5 on 2021-07-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0034_auto_20210715_0751'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='Instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
