# Generated by Django 3.2.5 on 2021-07-27 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0035_order_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_image',
            field=models.ImageField(blank=True, null=True, upload_to='Product/Offer'),
        ),
    ]
