# Generated by Django 3.2.5 on 2021-07-31 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_email_verify_email'),
        ('Product', '0037_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ManyToManyField(blank=True, related_name='get_all_user_request', to='Product.Product')),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.profile')),
            ],
        ),
    ]
