# Generated by Django 3.2.5 on 2021-07-31 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0038_product_request'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_request',
            name='product',
        ),
    ]
