# Generated by Django 3.2.5 on 2021-07-31 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0039_remove_product_request_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_request',
            name='profile',
        ),
    ]
