# Generated by Django 3.2.5 on 2021-07-31 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_email_verify_email'),
        ('Product', '0040_remove_product_request_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_request',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='product_request',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_all_user_request', to='Product.product'),
        ),
        migrations.AddField(
            model_name='product_request',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.profile'),
        ),
    ]
