# Generated by Django 3.2.5 on 2021-07-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0041_auto_20210731_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_request',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
