# Generated by Django 3.2.5 on 2021-07-31 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_email_verify_email'),
        ('Product', '0042_alter_product_request_created_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_request',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_user_product_request', to='customer.profile'),
        ),
    ]
