# Generated by Django 3.2.5 on 2021-08-01 06:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0053_delete_asdasdsad'),
        ('Product', '0043_alter_product_request_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.UUIDField(default=uuid.uuid4)),
                ('expiry_date', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.profile')),
            ],
        ),
    ]
