# Generated by Django 3.2.5 on 2021-08-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0044_special_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_code',
            name='discount_parsent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
