# Generated by Django 3.2.5 on 2021-08-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0045_special_code_discount_parsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='special_code',
            name='is_used',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
