# Generated by Django 3.2.5 on 2021-08-01 09:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0046_special_code_is_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='special_code',
            name='id',
        ),
        migrations.AlterField(
            model_name='special_code',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
