# Generated by Django 3.2.5 on 2021-08-01 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0053_delete_asdasdsad'),
        ('Product', '0047_auto_20210801_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='special_code',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_offer_code_obj', to='customer.profile'),
        ),
    ]
