# Generated by Django 3.2.5 on 2021-08-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0055_alter_user_location_user'),
        ('Product', '0048_alter_special_code_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='geo_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.user_location'),
        ),
    ]
