# Generated by Django 3.2.5 on 2021-08-04 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0059_chaldal_bottommenu_edit_need_realod'),
        ('Product', '0049_order_geo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='menu',
        ),
        migrations.AddField(
            model_name='product',
            name='menu',
            field=models.ManyToManyField(blank=True, related_name='product', to='root.Menu'),
        ),
    ]
