# Generated by Django 3.2.7 on 2021-09-18 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0051_alter_order_bag_json'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Special_Code',
        ),
    ]
