# Generated by Django 3.2.7 on 2021-09-18 16:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0056_c8message_is_rated'),
        ('Product', '0052_delete_special_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Special_Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_parsent', models.PositiveIntegerField(blank=True, null=True)),
                ('code', models.CharField(default=uuid.uuid4, max_length=70)),
                ('expiry_date', models.DateTimeField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(blank=True, default=False, null=True)),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_offer_code_obj', to='customer.profile')),
            ],
        ),
    ]
