# Generated by Django 4.0.3 on 2022-03-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0053_special_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_image',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
