# Generated by Django 4.0.3 on 2022-03-29 19:10

from django.db import migrations, models
import tkinter.tix


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0056_delivery_man_order_delivery_man'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_man',
            name='photo',
            field=models.ImageField(blank=tkinter.tix.Tree, null=True, upload_to='Product/Delivery_man'),
        ),
    ]
