# Generated by Django 4.0.3 on 2022-03-29 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0057_alter_delivery_man_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery_man',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='Product/Delivery_man'),
        ),
    ]
