# Generated by Django 4.0.3 on 2022-03-30 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0071_recordofsales_order'),
        ('Product', '0058_alter_delivery_man_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.payment_options_allow'),
        ),
    ]
