# Generated by Django 3.2.5 on 2021-07-30 02:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporate',
            name='image',
        ),
        migrations.AddField(
            model_name='corporate',
            name='svg',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
