# Generated by Django 3.2.5 on 2021-07-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0002_auto_20210730_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporate',
            name='svg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
