# Generated by Django 3.2.5 on 2021-07-30 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0003_alter_corporate_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
