# Generated by Django 3.2.5 on 2021-07-30 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0059_chaldal_bottommenu_edit_need_realod'),
        ('corporate', '0004_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='root',
            name='email',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.email'),
        ),
        migrations.AddField(
            model_name='root',
            name='mobile',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='root.mobile'),
        ),
    ]
