# Generated by Django 3.2.5 on 2021-07-30 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_email_verify_email'),
        ('corporate', '0005_auto_20210730_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate_customer',
            name='profile',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.profile'),
        ),
    ]
