# Generated by Django 3.2.5 on 2021-07-30 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0051_email_verify_email'),
        ('corporate', '0006_corporate_customer_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corporate_customer',
            name='profile',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_corporate_customer', to='customer.profile'),
        ),
    ]
