# Generated by Django 4.0.3 on 2022-03-30 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0009_corporate_svg_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corporate',
            name='svg',
        ),
    ]
