# Generated by Django 4.0.3 on 2022-03-31 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate', '0010_remove_corporate_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporate_customer',
            name='is_view',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
