# Generated by Django 3.2.5 on 2021-07-17 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_menu',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='support/<django.db.models.fields.CharField>'),
        ),
    ]
