# Generated by Django 3.2.5 on 2021-07-17 03:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_support_menu_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('occupation', models.CharField(blank=True, max_length=120, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='support/Team')),
                ('discription', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='support_menu',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='support/menu'),
        ),
    ]
