# Generated by Django 3.2.5 on 2021-07-18 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_auto_20210717_0905'),
    ]

    operations = [
        migrations.DeleteModel(
            name='support_stuf',
        ),
    ]
