# Generated by Django 3.2.5 on 2021-07-18 00:26

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_delete_support_stuf'),
    ]

    operations = [
        migrations.CreateModel(
            name='support_stuf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', ckeditor.fields.RichTextField()),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='get_stuff', to='support.support_menu')),
            ],
        ),
    ]
