# Generated by Django 3.2.5 on 2021-07-18 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_support_stuf'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_menu',
            name='slug',
            field=models.SlugField(default='', editable=False),
        ),
    ]
