# Generated by Django 3.2.5 on 2021-07-18 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0007_support_menu_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_menu',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
