# Generated by Django 3.2.5 on 2021-07-18 01:13

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0008_alter_support_menu_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_menu',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='support_stuf',
        ),
    ]
