# Generated by Django 4.0.3 on 2022-03-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0010_contactus'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='status',
            field=models.CharField(choices=[('Y', 'Read'), ('N', 'New Mail')], default='N', max_length=2),
        ),
    ]
