# Generated by Django 4.0.3 on 2022-03-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0056_c8message_is_rated'),
        ('support', '0011_contactus_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.profile'),
        ),
    ]
