# Generated by Django 4.0.3 on 2022-03-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0012_alter_contactus_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactus',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default='2022-02-03'),
            preserve_default=False,
        ),
    ]
