# Generated by Django 3.2.5 on 2021-08-02 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('root', '0059_chaldal_bottommenu_edit_need_realod'),
    ]

    operations = [
        migrations.CreateModel(
            name='slider_how_to_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='index/how_to_order_slider_img/')),
            ],
        ),
        migrations.CreateModel(
            name='why_chaldal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='index/why_chaldal_section/')),
                ('title', models.CharField(max_length=50)),
                ('discription', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='index_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, null=True, upload_to='index/menu/')),
                ('menu', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='root.menu')),
            ],
        ),
    ]
