# Generated by Django 3.2.7 on 2021-09-17 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_index_menu_svg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index_menu',
            name='svg',
        ),
    ]
