# Generated by Django 3.2.7 on 2021-09-17 01:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_remove_index_menu_svg'),
    ]

    operations = [
        migrations.AddField(
            model_name='index_menu',
            name='svg',
            field=models.FileField(blank=True, default=None, null=True, upload_to='index/menu_svg', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
        ),
    ]
