# Generated by Django 3.2.4 on 2021-06-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_setting',
            name='Email',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='Facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='Instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='Mobile',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='Twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='Youtube',
            field=models.URLField(blank=True, null=True),
        ),
    ]
