# Generated by Django 3.2.4 on 2021-06-21 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0002_auto_20210621_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_options_allow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to='payment_options')),
            ],
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='Email',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='Mobile',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
