# Generated by Django 3.2.4 on 2021-06-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0004_auto_20210621_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment_options_allow',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='payment_options/'),
        ),
    ]
