# Generated by Django 3.2.4 on 2021-06-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0005_alter_payment_options_allow_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basic_setting',
            options={'verbose_name_plural': 'BASIC ROOT SETTING'},
        ),
        migrations.RemoveField(
            model_name='basic_setting',
            name='Payment_allow',
        ),
        migrations.AddField(
            model_name='basic_setting',
            name='Payment_allow',
            field=models.ManyToManyField(to='root.Payment_options_allow'),
        ),
        migrations.AlterField(
            model_name='payment_options_allow',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
