# Generated by Django 3.2.4 on 2021-06-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0006_auto_20210621_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='delivery_allow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
    ]
