# Generated by Django 3.2.4 on 2021-06-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0007_delivery_allow'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='delivery_allow',
            new_name='delivery_label',
        ),
    ]
