# Generated by Django 3.2.4 on 2021-06-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0008_rename_delivery_allow_delivery_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_label',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
