# Generated by Django 3.2.4 on 2021-06-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0010_delivery_label_image_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='')),
                ('Image_link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
