# Generated by Django 3.2.4 on 2021-06-21 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0011_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_setting',
            name='allow_city',
            field=models.ManyToManyField(to='root.City', verbose_name='City'),
        ),
    ]
