# Generated by Django 3.2.4 on 2021-06-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0012_basic_setting_allow_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_setting',
            name='Favicon',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='basic_setting',
            name='LOGO',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
