# Generated by Django 3.2.4 on 2021-06-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0013_auto_20210622_0623'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_setting',
            name='Favicon_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basic_setting',
            name='LOGO_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='Favicon',
            field=models.ImageField(blank=True, null=True, upload_to="root/Other's"),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='LOGO',
            field=models.ImageField(blank=True, null=True, upload_to="root/Other's"),
        ),
        migrations.AlterField(
            model_name='city',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='root/City/'),
        ),
        migrations.AlterField(
            model_name='delivery_label',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='root/delivery_label/'),
        ),
        migrations.AlterField(
            model_name='payment_options_allow',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='root/payment_options/'),
        ),
    ]
