# Generated by Django 3.2.4 on 2021-06-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0015_auto_20210622_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_setting',
            name='Payment_allow',
            field=models.ManyToManyField(blank=True, null=True, to='root.Payment_options_allow'),
        ),
        migrations.RemoveField(
            model_name='basic_setting',
            name='delivery_allow',
        ),
        migrations.AddField(
            model_name='basic_setting',
            name='delivery_allow',
            field=models.ManyToManyField(blank=True, null=True, to='root.delivery_label'),
        ),
    ]
