# Generated by Django 3.2.4 on 2021-06-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0016_auto_20210622_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_setting',
            name='menu',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
