# Generated by Django 3.2.4 on 2021-06-22 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0017_basic_setting_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_setting',
            name='menu',
            field=models.JSONField(blank=True, help_text='Please add your Main menu and sub menu', null=True, verbose_name='Menu'),
        ),
    ]
