# Generated by Django 3.2.4 on 2021-06-22 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0018_alter_basic_setting_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Sub_Menu', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'BASIC ROOT SETTING',
            },
        ),
        migrations.RemoveField(
            model_name='basic_setting',
            name='menu',
        ),
    ]
