# Generated by Django 3.2.4 on 2021-06-22 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0019_auto_20210622_0803'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': "Menu's and Sub menu's"},
        ),
        migrations.AddField(
            model_name='menu',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='root/Menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='Image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
