# Generated by Django 3.2.4 on 2021-06-22 02:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0020_auto_20210622_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
