# Generated by Django 3.2.4 on 2021-06-22 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0021_menu_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
