# Generated by Django 3.2.4 on 2021-06-22 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0022_alter_menu_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='Date',
        ),
    ]
