# Generated by Django 3.2.4 on 2021-06-22 09:59

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0023_remove_menu_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='Email',
            field=models.ManyToManyField(blank=True, to='root.Email'),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='Mobile',
            field=models.ManyToManyField(blank=True, to='root.Mobile'),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='Payment_allow',
            field=models.ManyToManyField(blank=True, to='root.Payment_options_allow'),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='allow_city',
            field=models.ManyToManyField(blank=True, to='root.City', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='delivery_allow',
            field=models.ManyToManyField(blank=True, to='root.delivery_label'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='Phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(13)], verbose_name='Phone Number'),
        ),
    ]
