# Generated by Django 3.2.4 on 2021-06-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0025_alter_menu_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Update',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created'),
        ),
    ]
