# Generated by Django 3.2.4 on 2021-06-22 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0026_auto_20210622_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='records',
            field=models.JSONField(blank=True, editable=False, help_text="Show the menu's update record's", null=True),
        ),
    ]
