# Generated by Django 3.2.4 on 2021-06-22 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0027_menu_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ajsx_id',
            field=models.CharField(blank=True, help_text='It is the id of the menu .<strong>NO SPACE</strong>allow. Please requre the fill. <i>You can give any value<i>', max_length=30, null=True),
        ),
    ]
