# Generated by Django 3.2.4 on 2021-06-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_remove_product_menu'),
        ('root', '0029_alter_menu_ajsx_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='Product.Product'),
        ),
    ]
