# Generated by Django 3.2.4 on 2021-06-23 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0031_alter_menu_products'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='products',
        ),
    ]
