# Generated by Django 3.2.4 on 2021-06-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0033_auto_20210623_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_setting',
            name='Mobile_logo',
            field=models.ImageField(blank=True, null=True, upload_to="root/Other's"),
        ),
    ]
