# Generated by Django 3.2.4 on 2021-06-25 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0034_basic_setting_mobile_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_setting',
            name='Facebook_logo',
            field=models.ImageField(blank=True, null=True, upload_to="root/Other's"),
        ),
        migrations.AddField(
            model_name='basic_setting',
            name='Instagram_logo',
            field=models.ImageField(blank=True, null=True, upload_to="root/Other's"),
        ),
        migrations.AddField(
            model_name='basic_setting',
            name='Twitter_logo',
            field=models.ImageField(blank=True, null=True, upload_to="root/Other's"),
        ),
        migrations.AddField(
            model_name='basic_setting',
            name='Youtube_logo',
            field=models.ImageField(blank=True, null=True, upload_to="root/Other's"),
        ),
    ]
