# Generated by Django 3.2.4 on 2021-06-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0035_auto_20210625_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='social_media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='root/socal_media')),
            ],
        ),
        migrations.RemoveField(
            model_name='basic_setting',
            name='Facebook',
        ),
        migrations.RemoveField(
            model_name='basic_setting',
            name='Facebook_logo',
        ),
        migrations.RemoveField(
            model_name='basic_setting',
            name='Instagram',
        ),
        migrations.RemoveField(
            model_name='basic_setting',
            name='Instagram_logo',
        ),
        migrations.RemoveField(
            model_name='basic_setting',
            name='Twitter',
        ),
        migrations.RemoveField(
            model_name='basic_setting',
            name='Twitter_logo',
        ),
        migrations.RemoveField(
            model_name='basic_setting',
            name='Youtube',
        ),
        migrations.RemoveField(
            model_name='basic_setting',
            name='Youtube_logo',
        ),
        migrations.AddField(
            model_name='basic_setting',
            name='Social_media',
            field=models.ManyToManyField(blank=True, null=True, to='root.social_media'),
        ),
    ]
