# Generated by Django 3.2.4 on 2021-06-25 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0036_auto_20210625_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='social_media',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
