# Generated by Django 3.2.4 on 2021-06-25 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0037_social_media_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='root/features')),
            ],
        ),
        migrations.AddField(
            model_name='basic_setting',
            name='Features',
            field=models.ManyToManyField(blank=True, null=True, to='root.features'),
        ),
    ]
