# Generated by Django 3.2.4 on 2021-06-25 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0038_auto_20210625_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_setting',
            name='Favicon',
            field=models.ImageField(blank=True, null=True, upload_to='root/Others'),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='LOGO',
            field=models.ImageField(blank=True, null=True, upload_to='root/Others'),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='Mobile_logo',
            field=models.ImageField(blank=True, null=True, upload_to='root/Others'),
        ),
    ]
