# Generated by Django 3.2.4 on 2021-06-26 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0040_alter_basic_setting_social_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_setting',
            name='Features',
            field=models.ManyToManyField(blank=True, to='root.features'),
        ),
    ]
