# Generated by Django 3.2.5 on 2021-07-11 10:04

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0045_auto_20210711_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_setting',
            name='reusable_bag_price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='reusable_html_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
