# Generated by Django 3.2.5 on 2021-07-11 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0046_auto_20210711_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_setting',
            name='reusable_html_content',
        ),
        migrations.AlterField(
            model_name='basic_setting',
            name='reusable_bag_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
