# Generated by Django 3.2.5 on 2021-07-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0047_auto_20210711_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_setting',
            name='reusable_bag_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
