# Generated by Django 3.2.5 on 2021-07-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0048_alter_basic_setting_reusable_bag_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic_setting',
            name='reusable_bag_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
