# Generated by Django 3.2.5 on 2021-07-11 10:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0049_alter_basic_setting_reusable_bag_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_setting',
            name='reusable_html_content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
