# Generated by Django 3.2.5 on 2021-07-22 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0050_basic_setting_reusable_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_setting',
            name='side_bar_image',
            field=models.ImageField(blank=True, null=True, upload_to='root/Others'),
        ),
    ]
