# Generated by Django 3.2.5 on 2021-07-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0051_basic_setting_side_bar_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='page_image',
            field=models.ImageField(blank=True, null=True, upload_to='root/Menu'),
        ),
    ]
