# Generated by Django 3.2.5 on 2021-07-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0052_menu_page_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='page_banner_type',
            field=models.CharField(blank=True, choices=[('NM', 'Normal Banner'), ('AB', 'App Banner')], max_length=2, null=True),
        ),
    ]
