# Generated by Django 3.2.5 on 2021-07-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0053_menu_page_banner_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='page_banner_type',
            field=models.CharField(blank=True, choices=[('NM', 'Normal Banner'), ('AB', 'App Banner')], default='NM', max_length=2, null=True),
        ),
    ]
