# Generated by Django 3.2.5 on 2021-07-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0054_alter_menu_page_banner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='chaldal_bottomMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('json', models.JSONField()),
            ],
        ),
    ]
