# Generated by Django 3.2.5 on 2021-07-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0055_chaldal_bottommenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaldal_bottommenu',
            name='json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
