# Generated by Django 3.2.5 on 2021-07-30 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0056_alter_chaldal_bottommenu_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='chaldal_bottomMenu_edit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='chaldal_bottommenu',
            name='json',
        ),
        migrations.AlterField(
            model_name='chaldal_bottommenu',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Menu Name'),
        ),
        migrations.AddField(
            model_name='chaldal_bottommenu',
            name='menu',
            field=models.ManyToManyField(blank=True, to='root.chaldal_bottomMenu_edit'),
        ),
    ]
