# Generated by Django 3.2.5 on 2021-07-30 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0057_auto_20210730_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chaldal_bottommenu_edit',
            name='url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
