# Generated by Django 3.2.5 on 2021-07-30 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0058_alter_chaldal_bottommenu_edit_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaldal_bottommenu_edit',
            name='need_realod',
            field=models.BooleanField(default=False),
        ),
    ]
