# Generated by Django 3.2.7 on 2021-09-17 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0059_chaldal_bottommenu_edit_need_realod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='records',
        ),
    ]
