# Generated by Django 4.0.3 on 2022-03-19 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0060_remove_menu_records'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_setting',
            name='admin_login_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admin/login'),
        ),
    ]
