# Generated by Django 4.0.3 on 2022-03-23 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0061_basic_setting_admin_login_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_setting',
            name='Mini_Logo',
            field=models.ImageField(blank=True, null=True, upload_to='admin/Others'),
        ),
    ]
