# Generated by Django 4.0.3 on 2022-03-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0063_basic_setting_total_sell_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic_setting',
            name='Total_saved_money',
            field=models.BigIntegerField(blank=True, default='0'),
            preserve_default=False,
        ),
    ]
