# Generated by Django 4.0.3 on 2022-03-27 06:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0064_basic_setting_total_saved_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='Phone',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999999)], verbose_name='Phone Number'),
        ),
    ]
