# Generated by Django 4.0.3 on 2022-03-27 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0065_alter_mobile_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic_setting',
            name='reusable_html_content',
        ),
    ]
