# Generated by Django 4.0.3 on 2022-03-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0066_remove_basic_setting_reusable_html_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='is_use_home_menu',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
