# Generated by Django 4.0.3 on 2022-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0067_menu_is_use_home_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordOfSales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('sales', models.BigIntegerField()),
                ('product', models.BigIntegerField()),
            ],
        ),
    ]
