# Generated by Django 4.0.3 on 2022-03-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0068_recordofsales'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecordOfSales',
        ),
    ]
