# Generated by Django 4.0.3 on 2022-03-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0070_recordofsales'),
    ]

    operations = [
        migrations.AddField(
            model_name='recordofsales',
            name='order',
            field=models.BigIntegerField(default=100000),
            preserve_default=False,
        ),
    ]
