# Generated by Django 4.0.3 on 2022-03-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0071_recordofsales_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=700)),
                ('url', models.URLField(blank=True, null=True)),
                ('color', models.CharField(choices=[('R', 'RED'), ('G', 'GREEN'), ('B', 'BLUE'), ('P', 'PINK')], max_length=2)),
                ('is_new', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
