# Generated by Django 4.0.3 on 2022-03-31 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root', '0073_alter_notification_is_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=700, null=True),
        ),
    ]
